### ISSUE TITLE
None of crashes triggered

### ISSUE THREAD

**Issue by dordivaspo** [niklasb/bspfuzz#2]
Hi,
Thank you for your great work.I follow you aritcal step by step and got many crashes,but none of them triggered:(
I tryed triage.sh
```
root@ubuntu:~/bspfuzz-master/triage# sudo sysctl -w kernel.randomize_va_space=0
kernel.randomize_va_space = 0
root@ubuntu:~/bspfuzz-master/triage# ./triage.sh
Found 352 files
TODO 352 files
 [1/352] Processing /root/bspfuzz-master/fuzz/out/fuzzer1/crashes/id:000033,sig:11,src:000000,op:flip1,pos:367 / 0662ebf448aeb028bb47c4fa8201515e732da776
Traceback (most recent call last):
  File "./triage.py", line 137, in <module>
    crash = evaluate(fname)
  File "./triage.py", line 93, in evaluate
    return evaluate_impl(f)
  File "./triage.py", line 75, in evaluate_impl
    bt = process_bt(bt)
  File "./triage.py", line 45, in process_bt
    .strip().split(' = ')[1])
IndexError: list index out of range
root@ubuntu:~/bspfuzz-master/triage#
```

**Comment by niklasb** [comment]
Please let me know how you solved this and consider providing a pull request :)
